routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('index');

Route::middleware('guest')->group(function () {
    Route::controller(AuthController::class)->group(function () {
        Route::get('/login', 'login')->name('login');
        Route::get('/register', 'register')->name('register');

        Route::post('/login', 'authenticate')->name('authenticate');
        Route::post('/register', 'newUser')->name('newUser');
    });
});

Route::middleware('auth')->group(function () {
    Route::delete('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::middleware('role:admin')->group(function () {
        Route::resource('/subjects', SubjectController::class)->except(['show', 'index']);
    });
    Route::resource('/subjects', SubjectController::class)->only('show');
    Route::get('/level/{level}', [SubjectController::class, 'level'])->name('level');
    Route::get('/subject/{subject}', [SubjectController::class, 'subject'])->name('subject');
});

resources/views/home.blade.php
<x-main-layout title="Belajarin">
    @if (auth()->check())
        @role('user')
            <x-landing-user />
        @else
            <x-landing-admin />
        @endrole
    @else
        <x-landing-guest />
    @endif
</x-main-layout>

resources/views/level.blade.php
<x-main-layout title="Belajarin - Modul berdasarkan jengang {{ $level }}">
    <main class="pt-28 pb-10">
        <div class="container">
            <div class="flex justify-between items-center mb-4 gap-2">
                <h1 class="text-2xl font-black">Modul berdasarkan jenjang {{ $level }}!</h1>
                <a href="{{ route('index') }}"
                    class="py-2 font-bold px-6 rounded bg-zinc-100 text-zinc-600 text-sm">Back</a>
            </div>
            <div class="grid lg:grid-cols-4 sm:grid-cols-2 gap-4">
                @forelse ($modules as $row)
                    <a href="{{ route('subjects.show', $row->id) }}" class="p-6 rounded-xl border">
                        <h2 class="text-xl font-bold mb-1">{{ $row->title }}</h2>
                        <div class="flex items-center justify-between gap-1">
                            <p class="text-sm">Jenjang: {{ $row->level }}</p>
                            <span
                                class="text-xs py-1 px-2 rounded-full bg-blue-600 text-white">{{ $row->subject }}</span>
                        </div>
                    </a>
                @empty
                    <p>empty</p>
                @endforelse
            </div>
        </div>
    </main>
</x-main-layout>

resources/views/subject.blade.php
<x-main-layout title="Belajarin - Modul berdasarkan mata pelajaran {{ $subject }}">
    <main class="pt-28 pb-10">
        <div class="container">
            <div class="flex justify-between items-center mb-4 gap-2">
                <h1 class="text-2xl font-black">Modul berdasarkan mata pelajaran {{ $subject }}!</h1>
                <a href="{{ route('index') }}"
                    class="py-2 font-bold px-6 rounded bg-zinc-100 text-zinc-600 text-sm">Back</a>
            </div>
            <div class="grid lg:grid-cols-4 sm:grid-cols-2 gap-4">
                @forelse ($modules as $row)
                    <a href="{{ route('subjects.show', $row->id) }}" class="p-6 rounded-xl border">
                        <h2 class="text-xl font-bold mb-1">{{ $row->title }}</h2>
                        <div class="flex items-center justify-between gap-1">
                            <p class="text-sm">Jenjang: {{ $row->level }}</p>
                            <span
                                class="text-xs py-1 px-2 rounded-full bg-blue-600 text-white">{{ $row->subject }}</span>
                        </div>
                    </a>
                @empty
                    <p>empty</p>
                @endforelse
            </div>
        </div>
    </main>
</x-main-layout>