routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\SubjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('index');

Route::middleware('guest')->group(function () {
    Route::controller(AuthController::class)->group(function () {
        Route::get('/login', 'login')->name('login');
        Route::get('/register', 'register')->name('register');

        Route::post('/login', 'authenticate')->name('authenticate');
        Route::post('/register', 'newUser')->name('newUser');
    });
});

Route::middleware('auth')->group(function () {
    Route::delete('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::middleware('role:admin')->group(function () {
        Route::resource('/subjects', SubjectController::class)->except(['show', 'index']);
    });
    Route::resource('/subjects', SubjectController::class)->only('show');
    Route::get('/level/{level}', [SubjectController::class, 'level'])->name('level');
    Route::get('/subject/{subject}', [SubjectController::class, 'subject'])->name('subject');
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Subject extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function has_reads(): HasMany
    {
        return $this->hasMany(UserReadModule::class);
    }
    public function showSubject($id)
{
    $subject = Subject::find($id); // Assuming Subject is your model
    return view('subjects.show', compact('subject'));
}
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use App\Models\UserReadModule;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('subjects.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData =  $request->validate([
            'subject' => ['required', 'max:255'],
            'title' => ['required', 'max:255'],
            'level' => ['required', 'max:255'],
            'content' => ['required', 'max:65535'],
            'link' => ['nullable', 'url'],
        ]);

        // Tambahkan pengecekan apakah link YouTube ada sebelum mengupdate
        if ($request->has('link')) {
            $validatedData['link'] = $this->getYoutubeVideoId($request->link);
        }

        Subject::create($validatedData);

        return to_route('index')->with('success', 'Berhasil');
    }

    public function show(Subject $subject)
    {
        // $hasRead = UserReadModule::where('user_id', auth()->id())->where('subject_id', $subject->id)->first();
        UserReadModule::updateOrInsert(['user_id' => auth()->id()], ['subject_id' => $subject->id]);
        return view('subjects.show', ['subject' => $subject]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Subject $subject)
    {
        return view('subjects.edit', ['subject' => $subject]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Subject $subject)
    {
        $validatedData =  $request->validate([
            'subject' => ['required', 'max:255'],
            'title' => ['required', 'max:255'],
            'level' => ['required', 'max:255'],
            'content' => ['required', 'max:65535'],
            'link' => ['nullable', 'url'],
        ]);
        
        // Tambahkan pengecekan apakah link YouTube ada sebelum mengupdate
        if ($request->has('link')) {
            $validatedData['link'] = $this->getYoutubeVideoId($request->link);
        }

        $subject->update($validatedData);

        return to_route('index')->with('success', 'Berhasil');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Subject $subject)
    {
        $subject->delete();
        return to_route('index')->with('success', 'Berhasil');
    }

    public function level($level)
    {
        $modules = Subject::latest()->orderBy('title', 'asc')->where('level', $level)->get();
        return view('level', ['level' => $level, 'modules' => $modules]);
    }

    public function subject($subject)
    {
        $modules = Subject::latest()->orderBy('title', 'asc')->where('subject', $subject)->get();
        return view('subject', ['subject' => $subject, 'modules' => $modules]);
    }
    public function getYoutubeVideoId($url)
{
    // Extract video ID from YouTube URL
    $parsedUrl = parse_url($url);
    if (isset($parsedUrl['path'])) {
        $pathParts = explode('/', trim($parsedUrl['path'], '/'));
        return end($pathParts);
    }

        return '';
    }
}

resources/views/subjects/create.blade.php
<x-main-layout title="Belajarin - Tambah Modul">
    <main class="pt-28 pb-10 container">
        <div class="max-w-2xl mx-auto">
            <div class="flex justify-between items-center gap-2">
                <h1 class="text-2xl font-black mt-2 mb-4">Tambah Modul</h1>
                <a href="{{ route('index') }}"
                    class="py-2 font-bold px-6 rounded bg-zinc-100 text-zinc-600 text-sm">Back</a>
            </div>
            <form action="{{ route('subjects.store') }}" method="POST" class="space-y-4">
                @csrf
                <div class="grid gap-1">
                    <label for="title" class="font-medium text-zinc-800">Title</label>
                    <input type="text" name="title" id="title" value="{{ old('title') }}"
                        class="py-2 px-4 rounded border focus:outline-none">
                    @error('title')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                </div>
                <div class="grid sm:grid-cols-2 gap-4">
                    <div class="grid gap-1">
                        <label for="level" class="font-medium text-zinc-800">Level</label>
                        <input type="text" name="level" id="level" value="{{ old('level') }}"
                            class="py-2 px-4 rounded border focus:outline-none">
                        @error('level')
                            <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="grid gap-1">
                        <label for="subject" class="font-medium text-zinc-800">Subject</label>
                        <input type="text" name="subject" id="subject" value="{{ old('subject') }}"
                            class="py-2 px-4 rounded border focus:outline-none">
                        @error('subject')
                            <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="grid gap-1">
                    <label for="link" class="font-medium text-zinc-800">Link</label>
                    <input type="text" name="link" id="link" value="{{ old('subject') }}"
                        class="py-2 px-4 rounded border focus:outline-none">
                    @error('link')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                </div>
                <div class="space-y-1">
                    <label for="content" class="font-medium text-zinc-800">Content</label>
                    <textarea name="content" id="content"></textarea>
                    @error('content')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                </div>
                <button
                    class="py-2 font-bold px-6 rounded bg-indigo-100 text-indigo-600 text-sm">Submit</button>
            </form>
        </div>
    </main>
    <x-slot:js>
        <script>
            ClassicEditor
                .create(document.querySelector('#content'), {
                    licenseKey: '',
                })
                .then(editor => {
                    window.editor = editor;
                })
                .catch(error => {
                    console.error('Oops, something went wrong!');
                    console.error(
                        'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:'
                    );
                    console.warn('Build id: l4dyuz3v73cu-g0a98aaq8txd');
                    console.error(error);
                });
        </script>
    </x-slot:js>
</x-main-layout>

resources/views/subjects/edit.blade.php
<x-main-layout title="Belajarin - Edit Modul {{ $subject->id }} / {{ $subject->title }}">
    <main class="pt-28 pb-10 container">
        <div class="max-w-2xl mx-auto">
            <div class="flex justify-between items-center gap-2">
                <h1 class="text-2xl font-black mt-2 mb-4">Edit Modul</h1>
                <a href="{{ route('index') }}"
                    class="py-2 font-bold px-6 rounded bg-zinc-100 text-zinc-600 text-sm">Back</a>
            </div>
            <form action="{{ route('subjects.update', $subject->id) }}" method="POST" class="space-y-4">
                @csrf
                @method('PUT')
                <div class="grid gap-1">
                    <label for="title" class="font-medium text-zinc-800">Title</label>
                    <input type="text" name="title" id="title" value="{{ old('subject', $subject->title) }}"
                        class="py-2 px-4 rounded border focus:outline-none">
                    @error('title')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                </div>
                <div class="grid sm:grid-cols-2 gap-4">
                    <div class="grid gap-1">
                        <label for="level" class="font-medium text-zinc-800">Level</label>
                        <input type="text" name="level" id="level" value="{{ old('level', $subject->level) }}"
                            class="py-2 px-4 rounded border focus:outline-none">
                        @error('title')
                            <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="grid gap-1">
                        <label for="subject" class="font-medium text-zinc-800">Subject</label>
                        <input type="text" name="subject" id="subject"
                            value="{{ old('subject', $subject->subject) }}"
                            class="py-2 px-4 rounded border focus:outline-none">
                        @error('title')
                            <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="grid gap-1">
                    <label for="link" class="font-medium text-zinc-800">Link</label>
                    <input type="text" name="link" id="link" value="{{ old('subject', $subject->link) }}"
                        class="py-2 px-4 rounded border focus:outline-none">
                    @error('link')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                </div>
                <div class="space-y-1">
                    <label for="content" class="font-medium text-zinc-800">Content</label>
                    <textarea name="content" id="content">{{ old('content', $subject->content) }}</textarea>
                    @error('title')
                        <span class="text-red-600 text-sm font-medium">{{ $message }}</span>
                    @enderror
                    
                </div>
                <button
                    class="py-2 font-bold px-6 rounded bg-indigo-100 text-indigo-600 text-sm">Submit</button>
            </form>
        </div>
    </main>
    <x-slot:js>
        <script>
            ClassicEditor
                .create(document.querySelector('#content'), {
                    licenseKey: '',
                })
                .then(editor => {
                    window.editor = editor;
                })
                .catch(error => {
                    console.error('Oops, something went wrong!');
                    console.error(
                        'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:'
                    );
                    console.warn('Build id: l4dyuz3v73cu-g0a98aaq8txd');
                    console.error(error);
                });
        </script>
    </x-slot:js>
</x-main-layout>

resources/views/subjects/show.blade.php
<x-main-layout title="Belajarin - {{ $subject->title }}">
    <main class="pt-28 pb-10 container">
        <div class="max-w-2xl mx-auto">
            <div class="flex justify-between items-center gap-2">
                <h1 class="sm:text-4xl text-2xl font-black">{{ $subject->title }}</h1>
                <a href="{{ route('index') }}" class="py-2 font-bold px-6 rounded bg-zinc-100 text-zinc-600 text-sm">Back</a>
            </div>
            <div class="flex items-center gap-1 mt-4 mb-8">
                <span class="text-xs py-1 px-2 rounded-full bg-blue-600 text-white">{{ $subject->subject }}</span>
                <p class="text-sm">Jenjang: {{ $subject->level }}</p>
            </div>

            <div class="prose prose-zinc sm:prose-base prose-sm">
                {!! $subject->content !!}

            </div>

            @if($subject->link)
            <div class="video-preview">
                <br>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ $subject->link }}" frameborder="0" allowfullscreen></iframe>
            </div>
            @endif
            
        </div>
    </main>
</x-main-layout>